apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cilium-olm
  name: cilium-olm
  namespace: cilium
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cilium-olm
  template:
    metadata:
      labels:
        name: cilium-olm
    spec:
      containers:
        - command:
            - /usr/local/bin/helm-operator
            - run
            - --watches-file=watches.yaml
            - --enable-leader-election
            - --leader-election-id=cilium-olm
            - --zap-devel
            - --metrics-addr=localhost:8082
            - --health-probe-bind-address=localhost:8081
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELATED_IMAGE_CILIUM
              value: eBPF.cluster.test.nfvi.localdomain:5000/namespace-replace-target/cilium/cilium@sha256:6544a3441b086a2e09005d3e21d1a4afb216fae19c5a60b35793c8a9438f8f68
            - name: RELATED_IMAGE_HUBBLE_RELAY
              value: eBPF.cluster.test.nfvi.localdomain:5000/namespace-replace-target/cilium/hubble-relay@sha256:bc00f086285d2d287dd662a319d3dbe90e57179515ce8649425916aecaa9ac3c
            - name: RELATED_IMAGE_CILIUM_OPERATOR
              value: eBPF.cluster.test.nfvi.localdomain:5000/namespace-replace-target/cilium/operator-generic@sha256:4b58d5b33e53378355f6e8ceb525ccf938b7b6f5384b35373f1f46787467ebf5
            - name: RELATED_IMAGE_PREFLIGHT
              value: eBPF.cluster.test.nfvi.localdomain:5000/namespace-replace-target/cilium/cilium@sha256:6544a3441b086a2e09005d3e21d1a4afb216fae19c5a60b35793c8a9438f8f68
            - name: RELATED_IMAGE_CLUSTERMESH
              value: eBPF.cluster.test.nfvi.localdomain:5000/namespace-replace-target/cilium/clustermesh-apiserver@sha256:f7273ddb4c223e54827d1185d0c8f3b87966b05229358a224cdc3fe11a25fc72
            - name: RELATED_IMAGE_CERTGEN
              value: eBPF.cluster.test.nfvi.localdomain:5000/namespace-replace-target/cilium/certgen@sha256:2e0fc99ace29bbe5837718684920112a026bffc46f70efb38ea596c524e68819
            - name: RELATED_IMAGE_HUBBLE_UI_BE
              value: eBPF.cluster.test.nfvi.localdomain:5000/namespace-replace-target/cilium/hubble-ui-backend@sha256:45596ffc9afebec0014e3c1c068aa940a50fb394bd2407308f66a795fc0aeb5a
            - name: RELATED_IMAGE_HUBBLE_UI_FE
              value: eBPF.cluster.test.nfvi.localdomain:5000/namespace-replace-target/cilium/hubble-ui@sha256:d86764794c9f00c9cd89f553e300ea12c233f9b16a94cf67e19115ed6078c54a
            - name: RELATED_IMAGE_ETCD_OPERATOR
              value: eBPF.cluster.test.nfvi.localdomain:5000/namespace-replace-target/cilium/cilium-etcd-operator@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc
            - name: RELATED_IMAGE_NODEINIT
              value: eBPF.cluster.test.nfvi.localdomain:5000/namespace-replace-target/cilium/startup-script@sha256:c263d1678fb426842c0836358c1da7628d771126211694a3776c4b8500cbb215
            - name: RELATED_IMAGE_CLUSTERMESH_ETCD
              value: eBPF.cluster.test.nfvi.localdomain:5000/namespace-replace-target/coreos/etcd@sha256:a67fb152d4c53223e96e818420c37f11d05c2d92cf62c05ca5604066c37295e9
          image: eBPF.cluster.test.nfvi.localdomain:5000/namespace-replace-target/isovalent/cilium-olm@sha256:aed05a332413c8244b615d6b2f013e4fbc5ce7f65ed7f83213bc3605ae4dedce
          name: operator
          ports:
            - containerPort: 9443
              name: https
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      hostNetwork: true
      serviceAccount: cilium-olm
      terminationGracePeriodSeconds: 10
      tolerations:
        - operator: Exists
      volumes:
        - emptyDir: {}
          name: tmp
