---
- name: Play to populate image_hashes for relevant images
  hosts: localhost
  gather_facts: "{{ (setup_registry_service | default(True)) | bool }}"
  vars:
    destination_hosts:
      - registry_host
  pre_tasks:
    - name: pre-compute need to get hashes
      set_fact:
        run_get_hash: "{{ image_hashes | default({}) | length == 0  }}"
  roles:
    - role: get_image_hash
      when: run_get_hash


- name: Play populate mirror registry
  hosts: registry_host
  gather_facts: "{{ (setup_registry_service | default(True)) | bool }}"
  vars:
    config_file_path: /tmp/wip/config
    SETUP_REGISTRY_SERVICE: "{{ setup_registry_service | default(True)}}"
  roles:
    - role: populate_mirror_registry
      when: SETUP_REGISTRY_SERVICE == True
